version: '3.7'
services:
  turn_react:
    image: turn_react:latest
    expose:
      - 3000
    ports:
      - 3001:3000
    volumes:
      - './ui:/app'
      - '/app/node_modules'

  turn_data:
    image: turn_data:latest
    expose:
      - 5000
    ports:
      - 4000:5000
    environment:
      DISCOGS_USER_TOKEN: ${DISCOGS_USER_TOKEN}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: "password"
